export const factoryAbi = [
  {
    type: "function",
    name: "createToken",
    stateMutability: "payable",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      {
        name: "fees",
        type: "tuple",
        components: [
          { name: "buyFeeBps", type: "uint16" },
          { name: "sellFeeBps", type: "uint16" },
          { name: "feeCreatorBps", type: "uint16" },
          { name: "feeProtocolBps", type: "uint16" },
          { name: "feeBuybackBurnBps", type: "uint16" },
          { name: "tokenBurnOnBuyBps", type: "uint16" },
        ],
      },
      { name: "initialBuyMinTokens", type: "uint256" },
    ],
    outputs: [
      { name: "market", type: "address" },
      { name: "token", type: "address" },
    ],
  },
  {
    type: "function",
    name: "createFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allMarketsLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allMarkets",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "marketOfToken",
    stateMutability: "view",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "event",
    name: "TokenCreated",
    inputs: [
      { name: "market", type: "address", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
      { name: "initialBuyEth", type: "uint256", indexed: false },
      { name: "createFeePaid", type: "uint256", indexed: false },
    ],
  },
] as const;

export const marketAbi = [
  {
    type: "function",
    name: "buy",
    stateMutability: "payable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "minTokensOut", type: "uint256" },
    ],
    outputs: [{ name: "tokensToUser", type: "uint256" }],
  },
  {
    type: "function",
    name: "sell",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokensIn", type: "uint256" },
      { name: "minEthOut", type: "uint256" },
    ],
    outputs: [{ name: "ethToUser", type: "uint256" }],
  },
  {
    type: "function",
    name: "burnTokens",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getBuyQuote",
    stateMutability: "view",
    inputs: [{ name: "ethIn", type: "uint256" }],
    outputs: [
      { name: "tokensOut", type: "uint256" },
      { name: "tokensBurned", type: "uint256" },
      { name: "feeEth", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getSellQuote",
    stateMutability: "view",
    inputs: [{ name: "tokensIn", type: "uint256" }],
    outputs: [
      { name: "ethOut", type: "uint256" },
      { name: "feeEth", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "token",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "creator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "realEth",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "virtualEth",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "virtualToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "fees",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "buyFeeBps", type: "uint16" },
      { name: "sellFeeBps", type: "uint16" },
      { name: "feeCreatorBps", type: "uint16" },
      { name: "feeProtocolBps", type: "uint16" },
      { name: "feeBuybackBurnBps", type: "uint16" },
      { name: "tokenBurnOnBuyBps", type: "uint16" },
    ],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "burn",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
] as const;
